import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateMigration1762782472833 implements MigrationInterface {
    name = 'CreateMigration1762782472833'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`attribute_groups\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(200) NOT NULL, \`slug\` varchar(255) NULL, \`display_order\` int NOT NULL, UNIQUE INDEX \`IDX_cbf1498cdad86915f4906d2da6\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attribute_values\` (\`id\` int NOT NULL AUTO_INCREMENT, \`value\` varchar(255) NOT NULL, \`attribute_id\` int NOT NULL, \`display_color\` varchar(255) NULL, \`display_order\` int NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attributes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`is_public\` tinyint NOT NULL DEFAULT 0, \`group_id\` int NULL, \`type\` enum ('select', 'text', 'number', 'boolean', 'color', 'checkBox', 'radioButton') NOT NULL DEFAULT 'text', \`is_active\` tinyint NOT NULL DEFAULT 1, \`display_order\` int NOT NULL, \`is_variant\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_89afb34fd1fdb2ceb1cea6c57d\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`category_attributes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`category_id\` int NOT NULL, \`attribute_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`addresses\` (\`id\` int NOT NULL AUTO_INCREMENT, \`city\` varchar(255) NOT NULL, \`province\` varchar(255) NOT NULL, \`plaque\` varchar(255) NULL, \`unit\` varchar(255) NULL, \`address_line\` varchar(255) NULL, \`address_name\` varchar(255) NULL, \`recipient_name\` varchar(255) NULL, \`recipient_phone\` varchar(255) NULL, \`is_self\` tinyint NOT NULL DEFAULT 1, \`postal_code\` varchar(255) NOT NULL, \`is_primary\` tinyint NOT NULL DEFAULT 1, \`user_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d55ec35703b7d805f935a321f0\` (\`postal_code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`variant_attribute_values\` (\`id\` int NOT NULL AUTO_INCREMENT, \`variant_id\` int NOT NULL, \`attribute_id\` int NOT NULL, \`value_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`variants_product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`stock\` int NULL, \`price\` int NULL, \`sku\` varchar(255) NOT NULL, \`discount_amount\` decimal NOT NULL DEFAULT '0', \`discount_percent\` float NOT NULL DEFAULT '0', \`product_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`card_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`card_id\` int NOT NULL, \`product_id\` int NOT NULL, \`variant_id\` int NULL, \`quantity\` int NOT NULL, \`unit_price\` bigint NOT NULL, \`discount\` bigint NOT NULL DEFAULT '0', \`line_total\` bigint NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cards\` (\`id\` int NOT NULL AUTO_INCREMENT, \`status\` enum ('open', 'locked', 'abandoned') NOT NULL DEFAULT 'open', \`items_count\` int NOT NULL DEFAULT '0', \`total_quantity\` int NOT NULL DEFAULT '0', \`subtotal\` bigint NOT NULL DEFAULT '0', \`discount_total\` bigint NOT NULL DEFAULT '0', \`total\` bigint NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`product_id\` int NOT NULL, \`variant_id\` int NULL, \`quantity\` int NOT NULL, \`unit_price\` bigint NOT NULL, \`discount\` bigint NOT NULL DEFAULT '0', \`line_total\` bigint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoices\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`user_id\` int NOT NULL, \`subtotal\` bigint NOT NULL, \`discount_total\` bigint NOT NULL DEFAULT '0', \`total\` bigint NOT NULL, \`coupon_code\` varchar(255) NULL, \`coupon_discount_amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`total_payable\` bigint NOT NULL, \`status\` enum ('pending', 'paid', 'cancelled', 'shipped', 'delivered', 'refunded', 'failed') NOT NULL DEFAULT 'pending', \`payment_error_message\` varchar(255) NULL, \`payment_error_code\` varchar(100) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`address_id\` int NULL, \`status\` enum ('pending_approval', 'awaiting_payment', 'payment_confirmation_pending', 'preparing', 'shipping', 'delivered', 'not_delivered', 'expired', 'rejected', 'refunded', 'payment_failed') NOT NULL DEFAULT 'awaiting_payment', \`subtotal\` bigint NOT NULL, \`discount_total\` bigint NOT NULL DEFAULT '0', \`total\` bigint NOT NULL, \`payment_gateway_ref\` varchar(64) NULL, \`coupon_code\` varchar(255) NULL, \`coupon_discount_amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`is_manual\` tinyint NOT NULL DEFAULT 0, \`note\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` int NOT NULL, INDEX \`IDX_a922b820eeef29ac1c6800e826\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reviews\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`user_id\` int NOT NULL, \`rating\` tinyint NOT NULL DEFAULT '0', \`comment\` text NULL, \`is_approved\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`recent_views\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`product_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_790e4a7c64c17aa72b54757ff4\` (\`user_id\`, \`product_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`support_messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`support_id\` int NOT NULL, \`sender_id\` int NOT NULL, \`content\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supports\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`product_id\` int NULL, \`subject\` varchar(255) NOT NULL, \`status\` enum ('open', 'waiting', 'answered', 'closed') NOT NULL DEFAULT 'open', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`compare_products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`product_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`first_name\` varchar(100) NULL, \`last_name\` varchar(100) NULL, \`phone\` varchar(11) NULL, \`is_phone_verified\` tinyint NOT NULL DEFAULT 0, \`email\` varchar(100) NULL, \`password\` varchar(100) NULL, \`role\` enum ('super_admin', 'admin', 'user') NOT NULL DEFAULT 'user', \`api_token\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`email_verified_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`avatar_url\` varchar(255) NULL, \`media_id\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` (\`phone\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`medias\` (\`id\` int NOT NULL AUTO_INCREMENT, \`url\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`alt_text\` varchar(255) NULL, \`product_id\` int NULL, \`category_id\` int NULL, \`user_id\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(100) NOT NULL, \`slug\` varchar(255) NOT NULL, \`parent_id\` int NULL, \`level\` int NOT NULL DEFAULT '0', \`discount\` varchar(255) NULL, \`display_order\` int NOT NULL DEFAULT '0', \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_aa79448dc3e959720ab4c13651\` (\`title\`), UNIQUE INDEX \`IDX_420d9f679d41281f282f5bc7d0\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`helpers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`image\` varchar(255) NULL, \`product_id\` int NULL, UNIQUE INDEX \`REL_2057ac4d8a5db6c278470255e8\` (\`product_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`brands\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NULL DEFAULT '', \`logo\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_96db6bbbaa6f23cad26871339b\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_attribute_values\` (\`id\` int NOT NULL AUTO_INCREMENT, \`attribute_id\` int NOT NULL, \`product_id\` int NOT NULL, \`is_important\` tinyint NOT NULL DEFAULT 0, \`display_order\` int NOT NULL, \`value_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`price\` decimal NOT NULL, \`stock\` int NOT NULL, \`is_same_day_shipping\` tinyint NOT NULL DEFAULT 0, \`requires_preparation\` tinyint NOT NULL DEFAULT 0, \`preparation_days\` int NULL, \`is_limited_stock\` tinyint NOT NULL DEFAULT 0, \`discount_amount\` float NOT NULL DEFAULT '0', \`discount_percent\` float NOT NULL DEFAULT '0', \`is_featured\` tinyint NOT NULL DEFAULT 0, \`weight\` float NOT NULL DEFAULT '0', \`weight_unit\` enum ('کیلوگرم', 'گرم') NOT NULL DEFAULT 'کیلوگرم', \`description\` longtext NULL, \`is_visible\` tinyint NOT NULL DEFAULT 0, \`order_limit\` int NULL, \`category_id\` int NOT NULL, \`media_pinned_id\` int NULL, \`helper_id\` int NULL, \`brand_id\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`is_active\` tinyint NOT NULL DEFAULT 1, \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4c9fb58de893725258746385e1\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`wishlists\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`product_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_9c64a981c56ba677ac17f5fba6\` (\`user_id\`, \`product_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` decimal(10,2) NOT NULL, \`authority\` varchar(255) NOT NULL, \`ref_id\` bigint NULL, \`status\` enum ('pending', 'in_progress', 'success', 'failed', 'cancelled', 'verified', 'refunded') NOT NULL DEFAULT 'pending', \`message\` varchar(255) NOT NULL, \`gateway\` enum ('zarinpal', 'idpay', 'melat') NOT NULL DEFAULT 'zarinpal', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`order_id\` int NULL, \`user_id\` int NULL, UNIQUE INDEX \`IDX_539438bb24f0ae596bc58deeb1\` (\`authority\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`authority\` varchar(255) NULL, \`status\` varchar(50) NOT NULL, \`error_code\` int NULL, \`message\` varchar(255) NULL, \`ref_id\` varchar(100) NULL, \`ip\` varchar(45) NULL, \`user_agent\` varchar(255) NULL, \`payload\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`user_id\` int NULL, \`order_id\` int NULL, \`payment_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coupons\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`type\` enum ('percent', 'fixed') NOT NULL DEFAULT 'percent', \`amount\` decimal(10,2) NOT NULL, \`min_order_amount\` decimal(10,2) NULL, \`max_discount_amount\` decimal(10,2) NULL, \`start_date\` datetime NULL, \`end_date\` datetime NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`usage_limit\` int NULL, \`use_count\` int NOT NULL DEFAULT '0', \`for_first_order\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_e025109230e82925843f2a14c4\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coupon_users\` (\`coupon_id\` int NOT NULL, \`user_id\` int NOT NULL, INDEX \`IDX_1ed98e7e7561a0666d603bf242\` (\`coupon_id\`), INDEX \`IDX_396bd3ecb71da895d102e71a10\` (\`user_id\`), PRIMARY KEY (\`coupon_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coupon_products\` (\`coupon_id\` int NOT NULL, \`product_id\` int NOT NULL, INDEX \`IDX_edd5b3b5e912ada7e6d28277e2\` (\`coupon_id\`), INDEX \`IDX_4897e96fb4b70bd6ac1d4735ba\` (\`product_id\`), PRIMARY KEY (\`coupon_id\`, \`product_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coupon_categories\` (\`coupon_id\` int NOT NULL, \`category_id\` int NOT NULL, INDEX \`IDX_4746aa0d652b072947823dbaf4\` (\`coupon_id\`), INDEX \`IDX_c53cdd152a176ce12653afe1aa\` (\`category_id\`), PRIMARY KEY (\`coupon_id\`, \`category_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories_closure\` (\`id_ancestor\` int NOT NULL, \`id_descendant\` int NOT NULL, INDEX \`IDX_ea1e9c4eea91160dfdb4318778\` (\`id_ancestor\`), INDEX \`IDX_51fff5114cc41723e8ca36cf22\` (\`id_descendant\`), PRIMARY KEY (\`id_ancestor\`, \`id_descendant\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD CONSTRAINT \`FK_be02d0f6a15bc7a0d835f832b62\` FOREIGN KEY (\`attribute_id\`) REFERENCES \`attributes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attributes\` ADD CONSTRAINT \`FK_29eafc49196e788c35273ef214c\` FOREIGN KEY (\`group_id\`) REFERENCES \`attribute_groups\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_attributes\` ADD CONSTRAINT \`FK_55050a8a1b2d2f5202f226d4ac1\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_attributes\` ADD CONSTRAINT \`FK_6730826326fa81ff5511cb0981a\` FOREIGN KEY (\`attribute_id\`) REFERENCES \`attributes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_16aac8a9f6f9c1dd6bcb75ec023\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` ADD CONSTRAINT \`FK_5df07e5f75117c9eca2c2ba5051\` FOREIGN KEY (\`variant_id\`) REFERENCES \`variants_product\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` ADD CONSTRAINT \`FK_babb294d8dd3009691212302a83\` FOREIGN KEY (\`attribute_id\`) REFERENCES \`attributes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` ADD CONSTRAINT \`FK_6086b986a79029a5bd5571c8884\` FOREIGN KEY (\`value_id\`) REFERENCES \`attribute_values\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variants_product\` ADD CONSTRAINT \`FK_4d9dbb0c46905c65db1e8af57c5\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`card_items\` ADD CONSTRAINT \`FK_b5881f9d36423165eb8b31be05c\` FOREIGN KEY (\`card_id\`) REFERENCES \`cards\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`card_items\` ADD CONSTRAINT \`FK_fec9bcfd03cb68a80e29c340191\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`card_items\` ADD CONSTRAINT \`FK_09d582f4a66edaaac80b70b6342\` FOREIGN KEY (\`variant_id\`) REFERENCES \`variants_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD CONSTRAINT \`FK_1c54b595af68cc3870b651e11c9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_9263386c35b6b242540f9493b00\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_db2d0ea722e16e0fe8ab3bce111\` FOREIGN KEY (\`variant_id\`) REFERENCES \`variants_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_ea83c3b911906a3578de2340fdf\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_26daf5e433d6fb88ee32ce93637\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_d39c53244703b8534307adcd073\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_9482e9567d8dcc2bc615981ef44\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_728447781a30bc3fcfe5c2f1cdf\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recent_views\` ADD CONSTRAINT \`FK_8e9a6be3b12d39dec2af09ad9bb\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`recent_views\` ADD CONSTRAINT \`FK_a6a5ce0482aad2b79a9ac283d00\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_messages\` ADD CONSTRAINT \`FK_84a923dc563bf44ab4f6a97655a\` FOREIGN KEY (\`support_id\`) REFERENCES \`supports\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_messages\` ADD CONSTRAINT \`FK_db9f9d46849e30b9ac570db6eb6\` FOREIGN KEY (\`sender_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supports\` ADD CONSTRAINT \`FK_ba8fa43046519c0520db7e70f45\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`supports\` ADD CONSTRAINT \`FK_49ad355d0bc449067fb0058b5db\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`compare_products\` ADD CONSTRAINT \`FK_8377939f10e01321db7e301b21c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`compare_products\` ADD CONSTRAINT \`FK_14badea09a41a563561f8f6da73\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medias\` ADD CONSTRAINT \`FK_9a3c9e824622cab3843bbfcc66f\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medias\` ADD CONSTRAINT \`FK_2ac39c7d3213e1297003d0bedcd\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medias\` ADD CONSTRAINT \`FK_41d09f6d5c572f29cd001ed7edb\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_88cea2dc9c31951d06437879b40\` FOREIGN KEY (\`parent_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`helpers\` ADD CONSTRAINT \`FK_2057ac4d8a5db6c278470255e84\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_values\` ADD CONSTRAINT \`FK_61655fe2f6d179eced519392ced\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_values\` ADD CONSTRAINT \`FK_f1f04534a41f575a6def0710063\` FOREIGN KEY (\`attribute_id\`) REFERENCES \`attributes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_values\` ADD CONSTRAINT \`FK_823789b77c0b80f8876b90dd708\` FOREIGN KEY (\`value_id\`) REFERENCES \`attribute_values\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_039655ecefdf0a249c513104515\` FOREIGN KEY (\`media_pinned_id\`) REFERENCES \`medias\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9eb64185187f0d725ef1952f4d8\` FOREIGN KEY (\`helper_id\`) REFERENCES \`helpers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_1530a6f15d3c79d1b70be98f2be\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_b5e6331a1a7d61c25d7a25cab8f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_2662acbb3868b1f0077fda61dd2\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_b2f7b823a21562eeca20e72b006\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_427785468fb7d2733f59e7d7d39\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_logs\` ADD CONSTRAINT \`FK_1e910670d2be96480fe891ccb26\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_logs\` ADD CONSTRAINT \`FK_dce266ce9f4bc90221d677fc8a1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_logs\` ADD CONSTRAINT \`FK_6508afaa58d3f3e97c347631c0c\` FOREIGN KEY (\`payment_id\`) REFERENCES \`payments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`coupon_users\` ADD CONSTRAINT \`FK_1ed98e7e7561a0666d603bf2422\` FOREIGN KEY (\`coupon_id\`) REFERENCES \`coupons\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`coupon_users\` ADD CONSTRAINT \`FK_396bd3ecb71da895d102e71a10b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`coupon_products\` ADD CONSTRAINT \`FK_edd5b3b5e912ada7e6d28277e2c\` FOREIGN KEY (\`coupon_id\`) REFERENCES \`coupons\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`coupon_products\` ADD CONSTRAINT \`FK_4897e96fb4b70bd6ac1d4735bae\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`coupon_categories\` ADD CONSTRAINT \`FK_4746aa0d652b072947823dbaf48\` FOREIGN KEY (\`coupon_id\`) REFERENCES \`coupons\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`coupon_categories\` ADD CONSTRAINT \`FK_c53cdd152a176ce12653afe1aa6\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`categories_closure\` ADD CONSTRAINT \`FK_ea1e9c4eea91160dfdb4318778d\` FOREIGN KEY (\`id_ancestor\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories_closure\` ADD CONSTRAINT \`FK_51fff5114cc41723e8ca36cf227\` FOREIGN KEY (\`id_descendant\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`categories_closure\` DROP FOREIGN KEY \`FK_51fff5114cc41723e8ca36cf227\``);
        await queryRunner.query(`ALTER TABLE \`categories_closure\` DROP FOREIGN KEY \`FK_ea1e9c4eea91160dfdb4318778d\``);
        await queryRunner.query(`ALTER TABLE \`coupon_categories\` DROP FOREIGN KEY \`FK_c53cdd152a176ce12653afe1aa6\``);
        await queryRunner.query(`ALTER TABLE \`coupon_categories\` DROP FOREIGN KEY \`FK_4746aa0d652b072947823dbaf48\``);
        await queryRunner.query(`ALTER TABLE \`coupon_products\` DROP FOREIGN KEY \`FK_4897e96fb4b70bd6ac1d4735bae\``);
        await queryRunner.query(`ALTER TABLE \`coupon_products\` DROP FOREIGN KEY \`FK_edd5b3b5e912ada7e6d28277e2c\``);
        await queryRunner.query(`ALTER TABLE \`coupon_users\` DROP FOREIGN KEY \`FK_396bd3ecb71da895d102e71a10b\``);
        await queryRunner.query(`ALTER TABLE \`coupon_users\` DROP FOREIGN KEY \`FK_1ed98e7e7561a0666d603bf2422\``);
        await queryRunner.query(`ALTER TABLE \`payment_logs\` DROP FOREIGN KEY \`FK_6508afaa58d3f3e97c347631c0c\``);
        await queryRunner.query(`ALTER TABLE \`payment_logs\` DROP FOREIGN KEY \`FK_dce266ce9f4bc90221d677fc8a1\``);
        await queryRunner.query(`ALTER TABLE \`payment_logs\` DROP FOREIGN KEY \`FK_1e910670d2be96480fe891ccb26\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_427785468fb7d2733f59e7d7d39\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_b2f7b823a21562eeca20e72b006\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_2662acbb3868b1f0077fda61dd2\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_b5e6331a1a7d61c25d7a25cab8f\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_1530a6f15d3c79d1b70be98f2be\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9eb64185187f0d725ef1952f4d8\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_039655ecefdf0a249c513104515\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_values\` DROP FOREIGN KEY \`FK_823789b77c0b80f8876b90dd708\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_values\` DROP FOREIGN KEY \`FK_f1f04534a41f575a6def0710063\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_values\` DROP FOREIGN KEY \`FK_61655fe2f6d179eced519392ced\``);
        await queryRunner.query(`ALTER TABLE \`helpers\` DROP FOREIGN KEY \`FK_2057ac4d8a5db6c278470255e84\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_88cea2dc9c31951d06437879b40\``);
        await queryRunner.query(`ALTER TABLE \`medias\` DROP FOREIGN KEY \`FK_41d09f6d5c572f29cd001ed7edb\``);
        await queryRunner.query(`ALTER TABLE \`medias\` DROP FOREIGN KEY \`FK_2ac39c7d3213e1297003d0bedcd\``);
        await queryRunner.query(`ALTER TABLE \`medias\` DROP FOREIGN KEY \`FK_9a3c9e824622cab3843bbfcc66f\``);
        await queryRunner.query(`ALTER TABLE \`compare_products\` DROP FOREIGN KEY \`FK_14badea09a41a563561f8f6da73\``);
        await queryRunner.query(`ALTER TABLE \`compare_products\` DROP FOREIGN KEY \`FK_8377939f10e01321db7e301b21c\``);
        await queryRunner.query(`ALTER TABLE \`supports\` DROP FOREIGN KEY \`FK_49ad355d0bc449067fb0058b5db\``);
        await queryRunner.query(`ALTER TABLE \`supports\` DROP FOREIGN KEY \`FK_ba8fa43046519c0520db7e70f45\``);
        await queryRunner.query(`ALTER TABLE \`support_messages\` DROP FOREIGN KEY \`FK_db9f9d46849e30b9ac570db6eb6\``);
        await queryRunner.query(`ALTER TABLE \`support_messages\` DROP FOREIGN KEY \`FK_84a923dc563bf44ab4f6a97655a\``);
        await queryRunner.query(`ALTER TABLE \`recent_views\` DROP FOREIGN KEY \`FK_a6a5ce0482aad2b79a9ac283d00\``);
        await queryRunner.query(`ALTER TABLE \`recent_views\` DROP FOREIGN KEY \`FK_8e9a6be3b12d39dec2af09ad9bb\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_728447781a30bc3fcfe5c2f1cdf\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_9482e9567d8dcc2bc615981ef44\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_d39c53244703b8534307adcd073\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_26daf5e433d6fb88ee32ce93637\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_ea83c3b911906a3578de2340fdf\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_db2d0ea722e16e0fe8ab3bce111\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_9263386c35b6b242540f9493b00\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP FOREIGN KEY \`FK_1c54b595af68cc3870b651e11c9\``);
        await queryRunner.query(`ALTER TABLE \`card_items\` DROP FOREIGN KEY \`FK_09d582f4a66edaaac80b70b6342\``);
        await queryRunner.query(`ALTER TABLE \`card_items\` DROP FOREIGN KEY \`FK_fec9bcfd03cb68a80e29c340191\``);
        await queryRunner.query(`ALTER TABLE \`card_items\` DROP FOREIGN KEY \`FK_b5881f9d36423165eb8b31be05c\``);
        await queryRunner.query(`ALTER TABLE \`variants_product\` DROP FOREIGN KEY \`FK_4d9dbb0c46905c65db1e8af57c5\``);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` DROP FOREIGN KEY \`FK_6086b986a79029a5bd5571c8884\``);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` DROP FOREIGN KEY \`FK_babb294d8dd3009691212302a83\``);
        await queryRunner.query(`ALTER TABLE \`variant_attribute_values\` DROP FOREIGN KEY \`FK_5df07e5f75117c9eca2c2ba5051\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY \`FK_16aac8a9f6f9c1dd6bcb75ec023\``);
        await queryRunner.query(`ALTER TABLE \`category_attributes\` DROP FOREIGN KEY \`FK_6730826326fa81ff5511cb0981a\``);
        await queryRunner.query(`ALTER TABLE \`category_attributes\` DROP FOREIGN KEY \`FK_55050a8a1b2d2f5202f226d4ac1\``);
        await queryRunner.query(`ALTER TABLE \`attributes\` DROP FOREIGN KEY \`FK_29eafc49196e788c35273ef214c\``);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP FOREIGN KEY \`FK_be02d0f6a15bc7a0d835f832b62\``);
        await queryRunner.query(`DROP INDEX \`IDX_51fff5114cc41723e8ca36cf22\` ON \`categories_closure\``);
        await queryRunner.query(`DROP INDEX \`IDX_ea1e9c4eea91160dfdb4318778\` ON \`categories_closure\``);
        await queryRunner.query(`DROP TABLE \`categories_closure\``);
        await queryRunner.query(`DROP INDEX \`IDX_c53cdd152a176ce12653afe1aa\` ON \`coupon_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_4746aa0d652b072947823dbaf4\` ON \`coupon_categories\``);
        await queryRunner.query(`DROP TABLE \`coupon_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_4897e96fb4b70bd6ac1d4735ba\` ON \`coupon_products\``);
        await queryRunner.query(`DROP INDEX \`IDX_edd5b3b5e912ada7e6d28277e2\` ON \`coupon_products\``);
        await queryRunner.query(`DROP TABLE \`coupon_products\``);
        await queryRunner.query(`DROP INDEX \`IDX_396bd3ecb71da895d102e71a10\` ON \`coupon_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_1ed98e7e7561a0666d603bf242\` ON \`coupon_users\``);
        await queryRunner.query(`DROP TABLE \`coupon_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_e025109230e82925843f2a14c4\` ON \`coupons\``);
        await queryRunner.query(`DROP TABLE \`coupons\``);
        await queryRunner.query(`DROP TABLE \`payment_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_539438bb24f0ae596bc58deeb1\` ON \`payments\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_9c64a981c56ba677ac17f5fba6\` ON \`wishlists\``);
        await queryRunner.query(`DROP TABLE \`wishlists\``);
        await queryRunner.query(`DROP INDEX \`IDX_4c9fb58de893725258746385e1\` ON \`products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP TABLE \`product_attribute_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_96db6bbbaa6f23cad26871339b\` ON \`brands\``);
        await queryRunner.query(`DROP TABLE \`brands\``);
        await queryRunner.query(`DROP INDEX \`REL_2057ac4d8a5db6c278470255e8\` ON \`helpers\``);
        await queryRunner.query(`DROP TABLE \`helpers\``);
        await queryRunner.query(`DROP INDEX \`IDX_420d9f679d41281f282f5bc7d0\` ON \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_aa79448dc3e959720ab4c13651\` ON \`categories\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP TABLE \`medias\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`compare_products\``);
        await queryRunner.query(`DROP TABLE \`supports\``);
        await queryRunner.query(`DROP TABLE \`support_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_790e4a7c64c17aa72b54757ff4\` ON \`recent_views\``);
        await queryRunner.query(`DROP TABLE \`recent_views\``);
        await queryRunner.query(`DROP TABLE \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_a922b820eeef29ac1c6800e826\` ON \`orders\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`invoices\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP TABLE \`cards\``);
        await queryRunner.query(`DROP TABLE \`card_items\``);
        await queryRunner.query(`DROP TABLE \`variants_product\``);
        await queryRunner.query(`DROP TABLE \`variant_attribute_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_d55ec35703b7d805f935a321f0\` ON \`addresses\``);
        await queryRunner.query(`DROP TABLE \`addresses\``);
        await queryRunner.query(`DROP TABLE \`category_attributes\``);
        await queryRunner.query(`DROP INDEX \`IDX_89afb34fd1fdb2ceb1cea6c57d\` ON \`attributes\``);
        await queryRunner.query(`DROP TABLE \`attributes\``);
        await queryRunner.query(`DROP TABLE \`attribute_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_cbf1498cdad86915f4906d2da6\` ON \`attribute_groups\``);
        await queryRunner.query(`DROP TABLE \`attribute_groups\``);
    }

}
